name: Node.js CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
        # This block injects the GitHub data as local process.env variables
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
